#services:
#  version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      -  --db=dev-file
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"

volumes:
  keyclock-data:
    driver: local



#
#  db:
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: changePass
#
#
#
#  adminer:
#    image: adminer:latest
#    restart: always
#    ports:
#      - 8888:8080